const WHATSAPP_NUMBER = "50236529128";
const money = new Intl.NumberFormat("es-GT", { style: "currency", currency: "GTQ" });
const page = location.pathname.split('/').pop() || 'index.html';

const nav = [['index.html','Inicio'],['productos.html','Tienda Solar'],['servicios.html','Servicios'],['nosotros.html','Nosotros'],['contacto.html','Contacto']];
function whatsappUrl(text){return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`}
function layout(){
  document.querySelector('[data-header]').innerHTML=`<div class="topbar">☀ Envíos a todo el país · Asesoría personalizada · Equipos con garantía</div><header class="site-header"><div class="container nav"><a class="brand" href="index.html"><img class="brand-logo" src="assets/images/logo-esquisolar-icon.webp" alt="Logo de EsquiSolar" width="52" height="48"><span>EsquiSolar</span></a><button class="menu-toggle" aria-label="Abrir menú" aria-expanded="false">☰</button><nav class="nav-links" aria-label="Principal">${nav.map(([u,n])=>`<a href="${u}" ${page===u?'aria-current="page"':''}>${n}</a>`).join('')}</nav><div class="nav-actions"><a class="btn btn-primary" href="contacto.html#cotizacion">Solicitar cotización</a><button class="btn btn-outline cart-button" data-open-cart aria-label="Abrir carrito">🛒 <span class="cart-count" data-cart-count>0</span></button></div></div></header>`;
  document.querySelector('[data-footer]').innerHTML=`<footer class="footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="index.html"><img class="footer-logo" src="assets/images/logo-esquisolar.webp" alt="EsquiSolar — Energía solar, eficiencia, futuro" width="220" height="220"></a><p>Soluciones solares para ahorro, independencia energética y respaldo confiable.</p></div><div><h4>Enlaces</h4>${nav.map(([u,n])=>`<a href="${u}">${n}</a>`).join('')}</div><div><h4>Contacto</h4><a href="${whatsappUrl('Hola, EsquiSolar. Quiero información.')}" target="_blank" rel="noopener">WhatsApp: +502 3652 9128</a><span>esquisolar@gmail.com</span><span>4-59 zona 1, sobre la sexta avenida, Esquipulas. Local EsquiSolar</span></div><div><h4>Horario y redes</h4><span>Lunes a sábado, 8:00 a. m. a 5:00 p. m.</span><a href="#">[FACEBOOK]</a><a href="#">[INSTAGRAM]</a><a href="#">[TIKTOK]</a></div></div><div class="footer-bottom">© ${new Date().getFullYear()} EsquiSolar · Información y precios sujetos a confirmación.</div></div></footer><a class="whatsapp-float" href="${whatsappUrl('Hola, EsquiSolar. Quiero solicitar una cotización.')}" target="_blank" rel="noopener" aria-label="Contactar por WhatsApp">✆</a><div class="toast" role="status" aria-live="polite"></div>`;
  const toggle=document.querySelector('.menu-toggle'),links=document.querySelector('.nav-links');toggle.addEventListener('click',()=>{links.classList.toggle('open');toggle.setAttribute('aria-expanded',links.classList.contains('open'))});
}
function toast(message){const el=document.querySelector('.toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function sendQuote(form,title){if(!form.reportValidity())return;const data=new FormData(form);const lines=[`Hola, EsquiSolar. Quiero solicitar una cotización de ${title}:`,''];for(const [key,value] of data){if(value)lines.push(`${key}: ${value}`)}lines.push('','Quedo pendiente de su asesoría y confirmación.');window.open(whatsappUrl(lines.join('\n')),'_blank','noopener')}
document.addEventListener('DOMContentLoaded',()=>{layout();document.querySelectorAll('[data-wa]').forEach(a=>a.href=whatsappUrl(a.dataset.wa));document.querySelectorAll('[data-quote-form]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();sendQuote(f,f.dataset.quoteForm)}));});
